# Site
title:              For the Love of Guitars
bio:                'For the Love of Guitars is a space where I contribute my adoration and knowledge for the guitar and all things music by sharing valuable information, tips, advice, thoughts and guidance through articles, features, news, personal stories, videos and other media. I’m thrilled to know that the value of my expert contributions will have a positive impact in the world of guitars and music. For the Love of Guitars was made for guitar players, music lovers, future rock stars and guitar fans worldwide.'
description:        "For the Love of Guitars is a space made for guitar players, music lovers, future rock stars and guitar fans worldwide"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fortheloveofguitars.com" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:categories/:title/
markdown:           kramdown
remote-theme:       ajlkn/jekyll-theme-massively-src
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   iamgian-2
url:                "https://fortheloveofguitars.com"

# Social
analytics-id:       "UA-134142223-1"
twitter:            Gian_Solo
facebook:           go4thekill
instagram:          gian_solo
github:             default

# personal
location:           P.O. Box 6101, Burbank, CA. 91606
email:              fortheloveofgtrs@gmail.com
phone:              (818) 962-5972

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
