# Site
title:              GIAN SOLO
bio:                'Where Guitars, Guitarists and Life Unite'
description:        "Where Guitars, Guitarists and Life Unite"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iamgian.rocks" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
theme:              jekyll-theme-massively
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   mphmusic
url: ""

# Social
analytics-id:       "UA-98474063-1"
twitter:            Gian_Solo
facebook:           go4thekill
instagram:          gian_solo
github:             default

# personal
location:           North Hollywood, CA
email:              mphmusic@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
